# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Red_Cherry', models.BooleanField(default=False)),
                ('Wooden_Black', models.BooleanField(default=False)),
                ('Wooden_White', models.BooleanField(default=False)),
                ('Light_Walnut', models.BooleanField(default=False)),
                ('Maple', models.BooleanField(default=False)),
                ('Oak', models.BooleanField(default=False)),
                ('Glossy_White', models.BooleanField(default=False)),
                ('Other', models.BooleanField(default=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
