# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170329_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
