# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20170430_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.ProductCategory'),
        ),
    ]
