# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_productcategory_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='sub_category',
            new_name='parent_category',
        ),
    ]
