# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20170501_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_jp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_jp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_zh_hant',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
