# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20170514_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_jp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number_jp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number_zh_hant',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
