# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20170514_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(default='', max_length=10),
        ),
    ]
