# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('first_name', models.CharField(max_length=10)),
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('additional_note', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
