# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20161110_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
