# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20161113_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='side_note',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
