# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20161117_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_custom_made',
            field=models.BooleanField(default=False),
        ),
    ]
