# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20161118_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('U', 'Uncompleted'), ('C', 'Completed'), ('D', 'Deleted')], default='U', max_length=1),
        ),
    ]
