# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20161125_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='raw_price',
            field=models.IntegerField(default=0),
        ),
    ]
