# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_remove_invoice_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='drawing',
            field=models.ImageField(default='/static/common/delete.png', upload_to='drawings/'),
        ),
    ]
