# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_invoice_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='drawing',
            field=models.ImageField(default='/delete.png', upload_to='drawings/'),
        ),
    ]
