# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20161129_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='drawing',
        ),
    ]
