# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_remove_invoice_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='color',
            field=models.CharField(choices=[('Red_Cherry', 'R'), ('Wooden_Black', 'B'), ('Wooden_White', 'W'), ('Light_Walnut', 'L'), ('Maple', 'M')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='Light_Walnut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Maple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Red_Cherry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Wooden_Black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Wooden_White',
            field=models.BooleanField(default=False),
        ),
    ]
