# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20161129_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='color',
            field=models.CharField(choices=[('Red_Cherry', 'R'), ('Wooden_Black', 'B'), ('Wooden_White', 'W'), ('Light_Walnut', 'L'), ('Maple', 'M'), set(['Other', 'O'])], default='O', max_length=1),
        ),
    ]
