# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_product_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Other',
            field=models.BooleanField(default=True),
        ),
    ]
