# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_auto_20161129_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='product_serial',
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='color',
            field=models.CharField(choices=[(b'R', b'Red_Cherry'), (b'B', b'Wooden_Black'), (b'W', b'Wooden_White'), (b'L', b'Light_Walnut'), (b'M', b'Maple'), (b'O', b'Other')], default=b'O', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='invoice_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=20),
        ),
    ]
