# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_auto_20161207_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
