# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_invoice_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='drawing',
            field=models.ImageField(default=b'', upload_to=b'drawing'),
        ),
    ]
