# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_invoice_drawing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='first_created',
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
