# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_auto_20161215_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='drawing',
        ),
    ]
