# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_invoice_is_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_waiting',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[(b'U', b'Uncompleted'), (b'C', b'Completed'), (b'D', b'Deleted'), (b'W', b'Waiting')], default=b'U', max_length=1),
        ),
    ]
