# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_auto_20161218_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
