# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_invoicecustomproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='home_number',
            field=models.CharField(default=b'', max_length=8),
        ),
    ]
