# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_invoice_home_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecustomproduct',
            name='color',
        ),
    ]
