# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_remove_invoicecustomproduct_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecustomproduct',
            name='color',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
