# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_invoicecustomproduct_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Oak',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='color',
            field=models.CharField(choices=[(b'R', b'Red_Cherry'), (b'B', b'Wooden_Black'), (b'W', b'Wooden_White'), (b'L', b'Light_Walnut'), (b'M', b'Maple'), (b'A', b'Oak'), (b'O', b'Other')], default=b'O', max_length=1),
        ),
    ]
