# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0035_auto_20170123_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Oak',
            field=models.BooleanField(default=True),
        ),
    ]
