# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0039_auto_20170219_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicecustomproduct',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoiceproduct',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoiceproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
