# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0043_auto_20170222_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wardrobe',
            field=models.BooleanField(default=False),
        ),
    ]
