# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0045_auto_20170417_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Glossy_Champagne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Wooden_Champagne',
            field=models.BooleanField(default=False),
        ),
    ]
