# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0048_auto_20170426_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProductAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.InvoiceProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceproductaddon',
            name='product_addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.ProductAddon'),
        ),
    ]
