# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0049_auto_20170426_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[(b'V', b'Visa'), (b'E', b'EPS'), (b'C', '\u73fe\u91d1')], default=b'C', max_length=1),
        ),
    ]
