# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0050_auto_20170430_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
