# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0051_auto_20170505_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('serial_number',)},
        ),
        migrations.AddField(
            model_name='product',
            name='is_red_apple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_multiplies',
            field=models.FloatField(default=1.6),
        ),
    ]
