# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0052_auto_20170510_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_red_apple',
            new_name='red_apple',
        ),
    ]
